---
- name: Provision Emscripten Playground
  hosts: emscripten
  sudo: yes
  user: root
  roles:
      - BashEnvironment
      - role: nvm
        versions:
            - "0.10"
        default: "0.10"
      - Emscripten
