---
- name: Update Apt
  apt: update_cache=yes

- name: "Install build-essential package"
  apt: pkg="build-essential" state="latest"

- name: "Install libssl-dev package"
  apt: pkg="libssl-dev" state="latest"
